### ISSUE TITLE
如题

### ISSUE THREAD

**Issue by guomangbigcute** [XiaoMiku01/custom_bilibili_nft#5]
运行了一下，结果弹出这个错误：
  File "D:\custom_bilibili_nft-main\custom_bilibili_nft-main\nft.py", line 10
SyntaxError: Non-ASCII character '\xe4' in file D:\custom_bilibili_nft-main\custom_bilibili_nft-main\nft.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

[已退出进程，代码为 1]

**Comment by guomangbigcute** [comment]
好了已经解决了，在源代码最顶部加了#coding:utf-8
但是又出现了这个错误
  File "D:\custom_bilibili_nft-main\custom_bilibili_nft-main\nft.py", line 23
    def md5(data: Union[str, bytes]) -> str:
                ^
SyntaxError: invalid syntax

**Comment by XiaoMiku01** [comment]
你确定用的是python3?

**Comment by yarnra** [comment]
C:\Users\Lenovo\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/Users/Lenovo/PycharmProjects/pythonProject1/main.py
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\pythonProject1\main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

进程已结束,退出代码1


这个问题怎么弄
